{{- $fullName := include "factorio.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "factorio.name" . }}
    chart: {{ template "factorio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
      http:
        paths:
          - path: /*
            pathType: Prefix
            backend:
              service:
                Name: {{ $fullName }}
                Port: 
                  number: 34197
          - path: /*
            pathType: Prefix
            backend:
              service:
                Name: {{ $fullName }}
                Port:
                  number: 27015
{{ end }}
