{{- $fullName := include "factorio.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "factorio.name" . }}
    chart: {{ template "factorio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: LoadBalancer
  ports:
    - port: 34197
      targetPort: 34197
      name: factorio-1
    - port: 27015
      targetPort: 27015
      name: factorio-2
  selector:
    app: {{ $fullName }}
