apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "factorio.fullname" . }}-saves
  labels:
    app: {{ template "factorio.name" . }}
    chart: {{ template "factorio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  metadata:
    labels:
      app: {{ template "factorio.name" . }}
      release: {{ .Release.Name }}

  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: "1Gi"
