apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "factorio.fullname" . }}-saves
  labels:
    app: {{ template "factorio.name" . }}
    chart: {{ template "factorio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "1Gi"
