apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: {{ template "factorio.fullname" . }}
  labels:
    app: {{ template "factorio.name" . }}
    chart: {{ template "factorio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  serviceName: {{ template "factorio.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "factorio.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "factorio.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: factorio-udp
              containerPort: 34197
              protocol: UDP
            - name: factorio-tcp
              containerPort: 27015
              protocol: TCP
          volumeMounts:
            - name: factorio-data
              mountPath: /factorio
          securityContext:
            runAsUser: 0
      volumes:
        - name: factorio-data
          persistentVolumeClaim:
            claimName: {{ template "factorio.fullname" . }}-data
