kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: factorio-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: {{ template "factorio.fullname" . }}-storage-class
