image:
  repository: dtandersen/factorio
  tag: stable
  pullPolicy: IfNotPresent

ingress:
  annotations:
    #external-dns.alpha.kubernetes.io/hostname: "factorio.noahh.io., factorio.noahhuppert.com."
    #kubernetes.io/ingress.class: "gce"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
  hosts:
    - 192.168.10.91
    - 192.168.10.92
storageClass:
  create: true
