{{ if .Values.operatingMode == "factorio" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "factorio.fullname" . }}-multiplayer-server
  labels:
    app: {{ template "factorio.name" . }}-multiplayer-server
    chart: {{ template "factorio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

spec:
  type: NodePort
  ports:
    - name: factorio-udp
      port: 34197
      targetPort: 34197
      protocol: UDP 
    - name: factorio-tcp
      port: 27015
      targetPort: 27015
      protocol: TCP
  selector:
    app: {{ template "factorio.name" . }}-multiplayer-server
    release: {{ .Release.Name }}
{{ end }}
