{{ if .Values.operatingMode == "factorio" }}
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: {{ template "factorio.fullname" . }}-multiplayer-server
  labels:
    app: {{ template "factorio.name" . }}-multiplayer-server
    chart: {{ template "factorio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  serviceName: {{ template "factorio.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "factorio.name" . }}-multiplayer-server
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "factorio.name" . }}-multiplayer-server
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-multiplayer-server
          image: "{{ .Values.factorio.image.repository }}:{{ .Values.factorio.image.tag }}"
          imagePullPolicy: {{ .Values.factorio.image.pullPolicy }}
          ports:
            - name: factorio-udp
              containerPort: 34197
              protocol: UDP
            - name: factorio-tcp
              containerPort: 27015
              protocol: TCP
          volumeMounts:
            - name: factorio-saves
              mountPath: /factorio/saves
      volumes:
        - name: factorio-saves
          persistentVolumeClaim:
            claimName: {{ template "factorio.fullname" . }}-saves
{{ end }}
